# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pyzza

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install libgirepository1.0-dev python3-gi python3-gi-cairo libcairo2-dev libgtk-3-dev libvte-2.91-0
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygobject
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Debug Build
      run: |
        chmod +x ./scripts/debug && ./scripts/debug
    - name: Archive Debug Build
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'tar'
        directory: ./dist
        path: ./pyzza-debug
        filename: 'pyzza-debug.tar.gz'
    - name: Upload Debug Build
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: ./dist/pyzza-debug.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release Build
      run: |
        chmod +x ./scripts/build && ./scripts/build
    - name: Upload Release Build
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: ./dist/pyzza
        token: ${{ secrets.GITHUB_TOKEN }}
